version: '2'
services:
  nginx:
    build: ./nginx
    container_name: nginx
    environment: 
      # Y or N
      - SETUP_LETS_ENCRYPT_YN=N
      # enter an email address for registration if you enter Y above
      - SETUP_LETS_ENCRYPT_EMAIL=
      # enter the domains if you enter Y above
      - SETUP_LETS_ENCRYPT_DOMAINS=
    links:
      - testsite
    ports:
      - 443:443
      - 80:80      
  testsite:
    build: ./testsite
    container_name: testsite
